tensorchord/envd

README.md
=> docs: Edits on README.md

.github/workflows/CI.yml, .github/workflows/dependabot-reviewer.yml
=> ci: Auto-approve and merge dependabot PRs

.github/workflows/CI.yml
=> chore: Enable CI for PRs

.github/workflows/dependabot-reviewer.yml, .github/workflows/release.yml
=> fix(release): Change docker user

.github/workflows/CI.yml, README.md
=> chore(CI): Enable code coverage

.github/workflows/release.yml, .gitignore
=> fix: pypi sdist

.github/workflows/CI.yml
=> workflow: enable macOS in CI without conditions

examples/mnist/build.envd, pkg/app/up.go, pkg/builder/builder.go, pkg/docker/docker.go, pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/config/const.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
Closes https://github.com/tensorchord/envd/issues/216.
=> feat: Support specify number of GPUs

envd/cmd.py
=> fix: remove py wrapper traceback information

examples/mnist/README.md, examples/mnist/build_gpu.envd
Add cpu example & use it as default
=> Example: add cpu example

envd/api/config.py, envd/api/install.py
Signed-off-by: Popfido <wanghailin317@gmail.com>
Documentation of Ref: #291
=> doc: add conda commands documentation

.github/workflows/changelog.yaml, CHANGELOG.md, hack/changelog.sh
=> ci: Auto-generate changelog via GitHub Actions

pkg/app/app.go
hi, is [#352] enhanced in this way?
=> enhancement(CLI): Update the description of envd

.github/workflows/release.yml
=> fix: Add v before tags

envd/api/__init__.py
=> doc: Add universe api doc

cmd/envd/main.go, pkg/app/app.go, pkg/app/up.go, pkg/flag/consts.go, pkg/ssh/ssh.go
Ref #382 It is hard to debug errors.
=> fix: Output error details when debug flag is enabled

.goreleaser.yaml
=> feat(release): Support Homebrew in goreleaser

pkg/lang/ir/compile.go, pkg/lang/ir/conda.go, pkg/lang/ir/consts.go, pkg/lang/ir/editor.go, pkg/lang/ir/git.go, pkg/lang/ir/python.go, pkg/lang/ir/shell.go, pkg/lang/ir/system.go, pkg/lang/ir/types.go, pkg/lang/ir/util.go
=> feat(lang): Set default user to current

.github/workflows/release.yml
Fix https://github.com/tensorchord/envd/issues/393
=> bug: Fix source is released twice for macos and linux

.github/workflows/auto-merge.yml
=> ci: Auto-merge changelog PRs

pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/config/const.go, pkg/lang/ir/interface.go, pkg/lang/ir/r.go, pkg/lang/ir/types.go
=> feat: Support configuring CRAN mirror for R environment

ROADMAP.md
=> chore: Add a basic roadmap

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.md
=> docs: Add contact links and note on issue upvote

.goreleaser.yaml
=> release: Separate alpha and stable release in Homebrew

.gitignore
=> chore: remove duplicated item

README.md
=> fix: Fix typo

README.md
=> chore: Bump version v0.1.0

.goreleaser.yaml
=> fix: enable release with Homebrew only on stable versions

pkg/lang/ir/compile.go
=> chore: Remove redundant error check on ssh stage

CODE_OF_CONDUCT.md
=> docs: Add code of conduct document

pkg/lang/ir/system.go
seperate -> separate
Signed-off-by: Ikko Ashimine <eltociear@gmail.com>
=> chore: fix typo in system.go

Makefile
=> chore(Makefile): add default goal as `build`

pkg/docker/docker.go
=> fix: correct comments and unify receiver names and simplify some code

README.md
=> chore: Add roadmap in readme

pkg/docker/docker.go
replace ContainerInspect and Info with GetContainer and GetInfo
=> chore: replace ContainerInspect and Info with GetContainer and GetInfo

envd/api.go, pkg/builder/builder.go, pkg/lang/frontend/starlark/builtin/builtin.go, pkg/lang/frontend/starlark/install/install.go, pkg/lang/frontend/starlark/interpreter.go, pkg/lang/frontend/starlark/universe/universe.go, pkg/lang/ir/interface.go, pkg/lang/ir/parser/python.go
=> feat(lang): Support python requirements.txt in python_packages

ROADMAP.md
=> chore: fix typo in ROADMAP

pkg/app/bootstrap.go, pkg/app/build.go, pkg/app/destroy.go, pkg/app/pause.go, pkg/app/prune.go, pkg/app/resume.go, pkg/app/up.go
=> Enhancement(CLI): Use upper case in CLI description

pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/install/install.go, pkg/lang/frontend/starlark/universe/universe.go
Fix #498 
Snippet code: https://go.dev/play/p/vjWLVzqXnah
=> chore: Eliminate if condition in the conversion between starlark and go

pkg/app/app.go, pkg/app/bootstrap.go, pkg/app/build.go, pkg/app/context.go, pkg/app/context_create.go, pkg/app/context_ls.go, pkg/app/context_rm.go, pkg/app/context_use.go, pkg/app/prune.go, pkg/app/up.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/buildkitd/buildkitd.go, pkg/config/config.go, pkg/home/cache.go, pkg/home/config.go, pkg/home/context.go, pkg/home/manager.go, pkg/home/manager_test.go, pkg/types/envd.go
Ref #92 #510 
```
NAME:
envd context - Manage envd contexts
USAGE:
envd context command [command options] [arguments...]
COMMANDS:
create   Create envd context
ls       List envd contexts
use      Use the specified envd context
help, h  Shows a list of commands or help for one command
OPTIONS:
--help, -h  show help (default: false)
```
=> feat(CLI): Support context

README.md
=> fix: Add talk with us in README

pkg/lang/ir/system.go
=> fix: uid corrupted when run envd by root user

pkg/docker/docker.go
see https://github.com/tensorchord/envd/issues/525
=> feat: Add notice for users without permission to docker daemon

README.md
=> fix(README): Update coverage

base-images/build.sh, base-images/r4.2.Dockerfile, examples/mnist/main.py, examples/r-basic/build.envd, pkg/app/get_env.go, pkg/config/config.go, pkg/docker/docker.go, pkg/docker/label.go, pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/config/const.go, pkg/lang/ir/compile.go, pkg/lang/ir/editor.go, pkg/lang/ir/interface.go, pkg/lang/ir/julia.go, pkg/lang/ir/python.go, pkg/lang/ir/r.go, pkg/lang/ir/system.go, pkg/lang/ir/types.go, pkg/types/envd.go, pkg/types/label.go
Fix #490 
```py
def build():
base(os="ubuntu20.04", language="r")
install.r_packages([
"remotes",
"rlang",
])
config.rstudio_server()
shell("zsh")
```
```
NAME    ENDPOINT                        SSH TARGET      IMAGE           GPU     CUDA    CUDNN   STATUS          CONTAINER ID 
r-basic rstudio: http://localhost:34621 r-basic.envd    r-basic:dev     false   <none>  <none>  Up 12 minutes   1eb7d40e5a8a
```
=> feat(lang): Support RStudio server

envd/cmd.py
* fix https://github.com/tensorchord/envd/issues/546
=> fix: py cmd exit code

pkg/buildkitd/buildkitd.go, pkg/docker/docker.go
=> fix: add auto start buildkit container

pkg/lang/ir/conda.go
Signed-off-by: xuangong <xinglong@minimaxi.com>
=> fix: add -c for every single conda channel

pkg/ssh/ssh.go
=> chore: Use %w to format errors

pkg/lang/ir/python.go
=> fix: Pre-mkdir the .cache directory of user envd

cmd/envd/main.go
=> fix: Fix error handling issue

examples/custom-image/build.envd, pkg/lang/frontend/starlark/universe/universe.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/system.go, pkg/lang/ir/types.go
=> feat(lang): Support image in base

pkg/app/context_create.go, pkg/app/context_rm.go, pkg/app/context_use.go, pkg/app/init.go, pkg/home/manager_test.go, pkg/shell/zsh_test.go, pkg/ssh/config/ssh_config.go, pkg/ssh/ssh.go
Fix https://github.com/tensorchord/envd/issues/593
=> chore: Fix lint issues

pkg/lang/ir/conda.go, pkg/lang/ir/fs.go, pkg/lang/ir/python.go
=> fix: pre-create conda package cache directory

pkg/app/testdata/up-test/build.envd
=> chore: change to a tiny py lib to reduce test time

README.md
=> chore: Add gitpod badge

e2e/testdata/custom-image-test/build.envd, go.mod, go.sum, pkg/home/cache.go, pkg/home/config.go, pkg/home/context.go, pkg/home/manager_test.go, pkg/shell/zsh_test.go, pkg/ssh/config/key.go, pkg/util/fileutil/file.go
=> remove xdg, use $HOME/.config and $HOME/.cache

pkg/home/context.go, pkg/home/context_test.go
=> fix: context create with 'use'

examples/python-basic/build.envd, pkg/builder/build.go, pkg/builder/builder.go
=> fix(build): Fix image config

pkg/builder/util.go
=> chore: fix export cache warning

README.md
=> chore: Update discord badge

pkg/lang/frontend/starlark/install/install.go, pkg/lang/ir/parser/conda.go
=> fix: Fix lint issues in conda env yaml feature PR

examples/python-basic/build.envd, pkg/builder/builder.go, pkg/docker/docker.go, pkg/lang/frontend/starlark/interpreter.go, pkg/lang/frontend/starlark/io/const.go, pkg/lang/frontend/starlark/io/io.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/system.go, pkg/lang/ir/types.go
=> feat(lang): Add io.copy

pkg/lang/ir/shell.go
=> chore: skip starship prompt for customized image

docs/proposals/20220707-service-primitive.md
=> feat(lang): Add proposal for expose

.github/ISSUE_TEMPLATE/bug_report.md
=> chore: encourage user to provide envd version in bug report

examples/dgl/README.md, examples/dgl/build.envd, examples/dgl/train.py
Add an example running GAT training, use `io.mount` to mount datatset
=> example: add a dgl GAT example

pkg/lang/ir/editor.go
=> bug: fix notebook entry when setting conda channel

pkg/lang/ir/consts.go, pkg/lang/ir/interface.go, pkg/lang/ir/system.go
=> bug: allow multiple run command and use bash -c 

pkg/app/top.go
https://github.com/tensorchord/envd/issues/725
It was introduced by a hard code debug dirty code locally
=> Bug: fix SIGSEGV of envd top

pkg/app/bootstrap.go
before:
```
INFO[2022-08-05T18:30:24+08:00] You may have to restart your shell for autocomplete to get initialized (e.g. run "exec $SHELL")
v0.10.3: Pulling from moby/buildkit
59bf1c3509f3: Pull complete
cebf54714d9e: Pull complete
0b2c85935cbb: Pull complete
bb8c60c7d403: Pull complete
Digest: sha256:0dc312b04eac1b44cd2cad566deb1e886c753109208affbbec8384f381ff7f38
Status: Downloaded newer image for moby/buildkit:v0.10.3
INFO[2022-08-05T18:30:49+08:00] The buildkit is running at docker-container://envd_buildkitd
```
after:
```
INFO[2022-08-05T19:45:26+08:00] [1/3] Bootstrap SSH Key
INFO[2022-08-05T19:45:26+08:00] [2/3] Bootstrap autocomplete
INFO[2022-08-05T19:45:26+08:00] You may have to restart your shell for autocomplete to get initialized (e.g. run "exec $SHELL") …
```
=> feat(CLI): :recycle: refactor bootstrap command to show what's envd doing

.github/workflows/release.yml, base-images/build.sh
=> chore: Update release workflow

Makefile, e2e/e2e_helper.go, e2e/runtime_test.go, e2e/testdata/runtime/build.envd, e2e/testdata/runtime/demo.py, examples/python-basic/build.envd, go.mod, pkg/app/build.go, pkg/app/run.go, pkg/builder/builder.go, pkg/lang/frontend/starlark/interpreter.go, pkg/lang/frontend/starlark/runtime/const.go, pkg/lang/frontend/starlark/runtime/runtime.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go, pkg/ssh/ssh.go
=> feat(lang): Add a new func runtime.command

pkg/app/build.go, pkg/app/destroy.go, pkg/app/run.go, pkg/app/up.go, pkg/builder/builder.go, pkg/docker/docker.go, pkg/lang/ir/compile.go, pkg/util/fileutil/file.go
1. drop unnecessary filepath.Base
2. use filepath to replace path for OS safety
=> chore: :art: refactor to use filepath correctly

base-images/remote-cache/build-and-push-remote-cache.sh, pkg/lang/ir/compile.go
=> feat: Enable build for all languages

pkg/builder/builder.go
=> The workaround to fix the label loss

e2e/testdata/custom-image-test/build.envd, examples/custom-image/build.envd, pkg/app/up.go, pkg/builder/builder.go, pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/config/const.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
=> add entrypoint in custom image

Makefile, README.md, setup.py
=> chore: only support py3 for now

pkg/app/image.go
Issue: https://github.com/tensorchord/envd/issues/659
Signed-off-by: sunby <sunbingyi1992@gmail.com>
=> bug(CLI): fix short alias confusion

pkg/lang/ir/compile.go
=> fix: do not expose ports for custom image

pkg/docker/docker.go, pkg/lang/ir/editor.go
* not specified: generate a free port
* specified: use it (even if it's not free) (just let it crash)
=> fix: use defined jupyter port

README.md, envd/api/config/__init__.py, examples/mnist/build.envd, pkg/app/template/python.envd, pkg/lang/frontend/starlark/config/config.go, pkg/lang/ir/editor.go, pkg/lang/ir/editor_test.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
Signed-off-by: zhenguo.li <zhenguo.li@shopee.com>
=> fix: modify jupyter's authority from hash password to token string

README.md
1. update the contributing and dev links to the new location, this line L225
2. clean up tailing spaces
Signed-off-by: Wei Zhang <kweizh@gmail.com>
=> fix(docs): :memo: fix contributing and dev links, clean tailing space

pkg/metrics/widget.go
=> Fix the color display in wezterm

pkg/app/build.go, pkg/app/run.go, pkg/util/fileutil/file.go, pkg/util/fileutil/file_test.go
=> fix: -path and -file bug

envd/api/__init__.py, envd/api/config/__init__.py, envd/api/install/__init__.py, envd/api/io/__init__.py, envd/api/runtime/__init__.py, pkg/lang/frontend/starlark/config/config.go
=> doc: update python api doc

envd/api/__init__.py, envd/api/config/__init__.py, envd/api/install/__init__.py, envd/api/io/__init__.py, envd/api/runtime/__init__.py
Add instructions on how to modify the docs
=> docs: Update doc headers

envd/api/config/__init__.py, envd/api/io/__init__.py, envd/api/runtime/__init__.py
=> doc: daemon and expose

envd/api/runtime/__init__.py, examples/python-basic/build.envd, pkg/builder/builder.go, pkg/builder/util.go, pkg/lang/frontend/starlark/runtime/const.go, pkg/lang/frontend/starlark/runtime/runtime.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
related to 
* https://github.com/tensorchord/envd/issues/710
* https://github.com/tensorchord/envd/issues/157
=> feat: add runtime environments

pkg/lang/ir/compile.go
Signed-off-by: Wei Zhang <kweizh@gmail.com>
=> built: :hammer: use latest tag when not version found for cache

examples/streamlit-hello/build.envd, pkg/lang/ir/compile.go
=> feat(example): Add streamlit hello and remove bash -c in entrypoint

pkg/lang/ir/compile.go, pkg/lang/ir/system.go, pkg/version/version.go
=> fix: set to latest if git tag is empty

e2e/build_test.go, e2e/context_test.go, e2e/e2e_helper.go, e2e/get_env_test.go, e2e/quick_start_test.go, e2e/up_test.go
https://github.com/tensorchord/envd/issues/802
=> chore: fix e2e cleanup by introduce new helper function ResetEnvdApp

OWNERS
=> chore: Add OWNERS

envd/api/__init__.py, envd/api/runtime/__init__.py
=> doc: add include, refine others

.github/workflows/CI.yml, Makefile, e2e/docs/docs_test.go
=> test: enable e2e documentation test in CI

pkg/lang/ir/python.go
Fix https://github.com/tensorchord/envd/issues/828
=> bug: fix permission issue when pip install from git repo

README.md
=> fix: Update demo

envd/api/install/__init__.py, pkg/lang/frontend/starlark/install/install.go, pkg/lang/ir/interface.go, pkg/lang/ir/python.go, pkg/lang/ir/types.go
=> feat(lang): install.python_packages(local_wheels=[])

pkg/ssh/ssh.go
=> feat(cli): add msg when detach from container

e2e/cli/testdata/up-test/build.envd, e2e/docs/testdata/complex/build.envd, envd/api/config/__init__.py, envd/api/install/__init__.py, envd/api/io/__init__.py, examples/dgl/build.envd, examples/ianvs/build.envd, examples/python-basic/build.envd, examples/streamlit-mnist/build.envd, pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/install/const.go, pkg/lang/frontend/starlark/install/install.go, pkg/lang/frontend/starlark/io/io.go, pkg/lang/ir/consts.go, pkg/lang/ir/interface.go
=> refact: apt_source, io, config mode

pkg/builder/util.go, pkg/lang/ir/python.go, pkg/lang/ir/system.go, pkg/types/envd.go
=> refact: unify the path env

envd/api/io/__init__.py, envd/api/runtime/__init__.py, examples/dgl/build.envd, pkg/home/data.go, pkg/lang/frontend/starlark/data/rule.go, pkg/lang/frontend/starlark/io/const.go, pkg/lang/frontend/starlark/io/io.go, pkg/lang/frontend/starlark/runtime/const.go, pkg/lang/frontend/starlark/runtime/runtime.go
=> refact: io.mount => runtime.mount

.goreleaser.yaml, .goreleaser/envd-ssh.Dockerfile, .goreleaser/envd-sshd.Dockerfile, Makefile, base-images/build.sh, base-images/julia1.8rc1-ubuntu20.04.Dockerfile, base-images/python3.9-ubuntu20.04-cuda11.2.Dockerfile, base-images/python3.9-ubuntu20.04.Dockerfile, base-images/r4.2.Dockerfile, cmd/envd-sshd/main.go, pkg/lang/ir/compile.go
Upstream PR: https://github.com/tensorchord/envd/pull/864
=> chore(CLI): test new release for envd-sshd

.goreleaser.yaml, .goreleaser/envd-ssh.Dockerfile, .goreleaser/envd-sshd.Dockerfile, Makefile, base-images/build.sh, base-images/julia1.8rc1-ubuntu20.04.Dockerfile, base-images/python3.9-ubuntu20.04-cuda11.2.Dockerfile, base-images/python3.9-ubuntu20.04.Dockerfile, base-images/r4.2.Dockerfile, cmd/envd-sshd/main.go, pkg/lang/ir/compile.go
* chore(CLI): Rename envd-ssh to envd-sshd
Signed-off-by: Yuedong Wu <dwcn22@outlook.com>
* trim whitespaces
Signed-off-by: Yuedong Wu <dwcn22@outlook.com>
Signed-off-by: Yuedong Wu <dwcn22@outlook.com>
=> chore(CLI): test new release for envd-sshd (#866)

.github/workflows/auto-merge.yml
* fix https://github.com/tensorchord/envd/runs/8297324014?check_suite_focus=true
=> chore: fix ci auto merge token

pkg/docker/docker.go, pkg/lang/frontend/starlark/runtime/runtime.go, pkg/lang/ir/compile.go, pkg/lang/ir/conda.go, pkg/lang/ir/consts.go, pkg/lang/ir/editor.go, pkg/lang/ir/git.go, pkg/lang/ir/python.go, pkg/lang/ir/shell.go, pkg/lang/ir/util.go, pkg/util/fileutil/file.go
=> refact: add envd home path func

pkg/lang/ir/compile.go, pkg/shell/install.sh
=> chore: shell exit with `set -euo pipefail`

pkg/lang/ir/shell.go
In case of users don't have fonts to render the emoji.
=> chore: replace starship status symbol to common meanings

pkg/lang/ir/consts.go, pkg/lang/ir/git.go
=> fix: typo for git config file

pkg/lang/ir/editor.go, pkg/lang/ir/editor_test.go
=>  fix: Fix jupyter in root

.github/workflows/release.yml
=> chore: Enable write-all in release yaml

.goreleaser.yaml
=> chore(goreleaser): Skip homebrew

.github/workflows/release.yml
=> fix: Use macos 11

README.md
Signed-off-by: Nino <52693877+lilylee1874@users.noreply.github.com>
=> chore: add logo

.github/workflows/CI.yml, .github/workflows/daily.yml, Makefile, e2e/cli/bytecode_hash_test.go, e2e/cli/quick_start_test.go, e2e/cli/suite_test.go, e2e/docs/docs_gpu_test.go, e2e/docs/docs_test.go, e2e/docs/suite_test.go, e2e/e2e_helper.go, e2e/language/python_test.go, e2e/language/runtime_test.go, e2e/language/suite_test.go, examples/conda/build.envd, examples/dgl/build.envd, examples/mnist/build.envd, pkg/app/destroy.go
=> fix: e2e doc test

base-images/remote-cache/build.envd, pkg/lang/ir/system.go
=> fix: cuda tag

e2e/cli/context_test.go, pkg/app/bootstrap.go, pkg/app/context_create.go, pkg/app/context_ls.go, pkg/app/prune.go, pkg/builder/builder.go, pkg/home/context.go, pkg/home/context_test.go, pkg/home/manager.go, pkg/home/manager_test.go, pkg/types/envd.go
=> feat(CLI): Support runner in context

.github/workflows/CI.yml, .golangci.yml
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
=> *: upgrade golangci-linter and add noloopclosure

pkg/util/starlarkutil/stringslice_test.go
=> Chore(test): Add test cases for pkg/util/starlarkutil

.github/workflows/CI.yml, .golangci.yml, pkg/builder/builder.go, pkg/builder/util_test.go, pkg/editor/vscode/vscode_test.go, pkg/lang/ir/conda.go, pkg/lang/ir/custom.go, pkg/lang/ir/editor.go, pkg/lang/ir/fs.go, pkg/lang/ir/system.go, pkg/metrics/helper.go, pkg/progress/progressui/display.go, pkg/remote/sshd/sshd.go, pkg/ssh/config/ssh_config.go
=> fix: Remove dump checkout and remove pre-commit

.github/workflows/release.yml, base-images/remote-cache/build-and-push-remote-cache.sh
=> chore: Split cache build

README.md
Signed-off-by: Yilong Li <liyilongko@gmail.com>
=> docs: add star history chart to README

cmd/envd-sshd/main.go, e2e/docs/docs_test.go, pkg/app/bootstrap.go, pkg/app/init.go, pkg/app/login.go, pkg/lang/frontend/starlark/interpreter.go, pkg/remote/sshd/sshd.go, pkg/ssh/ssh.go
=> chore: update deprecated function and lint

pkg/app/build.go, pkg/app/up.go, pkg/envd/docker.go
support [#892](https://github.com/tensorchord/envd/issues/892)
=> feat(build): detect if the current environment is running before building (#892)

e2e/e2e_helper.go, pkg/app/build.go, pkg/app/destroy.go, pkg/app/env.go, pkg/app/env_describe.go, pkg/app/image.go, pkg/app/image_describe.go, pkg/app/pause.go, pkg/app/resume.go, pkg/app/run.go, pkg/app/top.go, pkg/app/up.go, pkg/app/version.go, pkg/buildkitd/buildkitd.go, pkg/envd/factory.go
=> fix: Remove hard code docker in envd engine init

pkg/home/auth_test.go
=> chore(test): Add test cases for pkg/home/auth.go

pkg/app/image.go, pkg/app/image_remove.go
=> feat(cli): add `envd images remove` command

pkg/app/bootstrap.go
Signed-off-by: XRW <elizax@163.com>
=> fix(CLI): Fix a typo

pkg/app/up.go, pkg/builder/builder.go
=> fix: Add two debug logs

e2e/language/python_test.go, e2e/language/testdata/python/conda_channel/build.envd, e2e/language/testdata/python/conda_channel/env.yaml, pkg/lang/ir/conda.go
=> bug: fix explicit channel setting with conda env.yaml

pkg/app/env_describe.go
=> feat: support using current directory name as env name

pkg/home/auth_test.go
=> bug: Fix flaky auth test

pkg/lang/ir/user.go
=> chore: pre init envd config and cache dir

pkg/app/destroy.go
=> feat: add `envd down` as an alias for `envd destroy`

pkg/lang/ir/python.go
=> chroe: make python package after apt package

docs/proposals/20220707-base-image.md
Preview: https://github.com/gaocegege/envd/blob/base/docs/proposals/20220707-base-image.md
=> feat(lang): Add proposal for custom base image

Makefile, setup.py
=> bug: fix install from pypi source release

e2e/cli/build_test.go, e2e/cli/up_test.go, pkg/app/destroy.go, pkg/docker/docker.go, pkg/envd/docker.go, pkg/envd/engine.go, pkg/envd/envdserver.go
=> chore(CLI): Move destroy logic from docker to envd engine.

base-images/envd/build.sh, base-images/envd/envd-daemonless.Dockerfile
=> fix: Fix build.sh

examples/python-basic/build.envd, go.mod, go.sum, pkg/app/create.go, pkg/envd/envdserver.go, pkg/envd/types.go, pkg/lang/ir/compile.go, pkg/lang/ir/supervisor.go, pkg/ssh/ssh.go, pkg/types/label.go
This PR is to add a new goroutine to forward the backend pod's ports to the local host port.
Close #958 
=> feat: Support forward

pkg/app/up.go, pkg/envd/docker.go, pkg/envd/engine.go, pkg/envd/envdserver.go, pkg/envd/types.go
=> feat(CLI): Support envd-server in up command

pkg/lang/ir/compile.go, pkg/lang/ir/julia.go, pkg/lang/ir/python.go, pkg/lang/ir/r.go, pkg/lang/ir/supervisor.go, pkg/lang/ir/system.go
Refactor the IR compile progress.
=> chore: Refactor the IR

pkg/app/destroy.go, pkg/envd/docker.go, pkg/envd/envdserver.go, pkg/lang/ir/compile.go, pkg/lang/ir/supervisor.go, pkg/lang/ir/system.go
=> feat: support envd server destroy env

pkg/app/app.go
=> fix(CLI): Fix format for app

pkg/home/auth.go
=> fix: auth with the same name

envd/api/__init__.py, pkg/lang/frontend/starlark/universe/universe.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/system.go, pkg/lang/ir/types.go
* fix #1091 
This could be verified with:
```py
def build():
base(os="ubuntu20.04", language="python3")
run(["sleep 5 && python -c \"import os; print(os.environ)\" > /tmp/run.txt"])
```
=> feat: support build time run without mount host

go.mod, go.sum, pkg/app/app.go, pkg/app/build.go, pkg/app/destroy.go, pkg/app/env_ls.go, pkg/app/image_prune.go, pkg/app/telemetry/reporter.go, pkg/app/top.go, pkg/app/up.go, pkg/flag/consts.go
Close #241 
Some commands return so fast. The main goroutine returns too fast to send the async telemetry event.
=> feat: Add telemetry with the help of segment.io

pkg/app/app.go, pkg/app/debug.go, pkg/app/debug_llb.go, pkg/app/telemetry/reporter.go, pkg/builder/builder.go
Fix https://github.com/tensorchord/envd/issues/896
```
./bin/envd --debug debug llb -p ./examples/python-basic --dot > a.dot
dot -Tpng a.dot -o a.png
```
=> feat(debug): Add llb export

pkg/lang/ir/conda.go, pkg/lang/ir/python.go
=> fix: Remove cwd in conda to enable remote cache

pkg/app/build.go, pkg/app/destroy.go, pkg/app/env_ls.go, pkg/app/image_prune.go, pkg/app/telemetry/reporter.go, pkg/app/top.go, pkg/app/up.go
=> feat: record cmd duration in telemetry

pkg/app/create.go, pkg/app/up.go, pkg/envd/docker.go, pkg/envd/types.go, pkg/lang/frontend/starlark/runtime/runtime.go, pkg/types/envd.go
https://github.com/tensorchord/envd/issues/1111
=> feat: expose support listen addr

envd/api/runtime/__init__.py
=> docs: add api docs for expose

pkg/app/image_remove.go
=> feat(cli): Add alias rm to envd image remove

base-images/remote-cache/build.envd, e2e/docs/testdata/complex/build.envd, envd/api/install/__init__.py, examples/conda/build.envd, examples/dgl/build.envd, examples/mnist/build.envd, examples/pytorch-profiler/build.envd, examples/stable-diffusion/build.envd
=> chore: update cuda & cudnn version

.github/semantic.yml
=> ci: Add semantic PR check

go.mod, go.sum, pkg/builder/util.go, pkg/lang/ir/compile.go, pkg/lang/ir/custom.go, pkg/lang/ir/system.go, pkg/types/envd.go
=> feat: Fetch base image metadata

pkg/lang/ir/supervisor.go
=> fix: horust cache

pkg/lang/ir/compile.go, pkg/lang/ir/supervisor.go, pkg/lang/ir/system.go
=> fix: pre mkdir for runtime mount

.github/workflows/release.yml, base-images/remote-cache/build-and-push-remote-cache.sh
=> fix: cuda tag in image cache

README.md
* fix https://github.com/tensorchord/envd/issues/983
=> chore: update envd cat wink to svg light/dark mode

README.md
Signed-off-by: shaoanianche <github@duanfei.org>
=> chore: update envd explain light/dark mode

examples/stable-diffusion/build.envd, examples/stable-diffusion/main.py
Fix this issue #1165 
Two things:
1. fix stable diffusion demo via b/c huggingface api change
2. add fp16 support for stable diffusion demo
=> fix stable diffusion demo via b/c huggingface api change

go.mod, go.sum, pkg/app/env_ls.go, pkg/types/envd.go
* fix https://github.com/tensorchord/envd/issues/1045
This requires the new release of the envd-server after merging https://github.com/tensorchord/envd-server/pull/59.
=> refact: move env to server

pkg/builder/util.go, pkg/envd/docker.go
=> fix: Move user to image config

pkg/builder/builder.go, pkg/lang/ir/util.go
This PR is to solve the followings problems:
- More and more deps files such as requirements.txt
- Include syntax that import other files
=> chore: optimized the cache mechanism

README.md, pkg/lang/ir/supervisor.go
=> fix: daemon command

e2e/docs/docs_test.go, e2e/docs/testdata/envdlib/build.envd
=> test: readme envdlib

.github/workflows/release.yml, pkg/app/app.go, pkg/flag/consts.go, pkg/lang/ir/util.go
=> feat: support build owner

pkg/lang/ir/custom.go, pkg/lang/ir/system.go
=> fix: only mkdir /home/envd/* when image==nil

.goreleaser.yaml
ref:
* https://github.com/goreleaser/goreleaser/blob/8cc24a55a2622502e8c3117d4c0e216b47cb4f82/internal/client/github.go#L66
* https://goreleaser.com/customization/changelog/?h=changelog#changelog
=> chore: add github user name to changelog & release note

envd/api/runtime/__init__.py, pkg/lang/frontend/starlark/runtime/runtime.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
=> feat: support add new dir to runtime PATH

.github/workflows/release.yml, .goreleaser.yaml
=> chore: Support arm macOS build

go.sum, pkg/app/app.go, pkg/app/bootstrap.go, pkg/app/completion.go, pkg/autocomplete/bash.go, pkg/autocomplete/zsh.go
Usage:
```
NAME:
envd completion - Install shell completion scripts for envd
USAGE:
envd completion [command options] [arguments...]
CATEGORY:
Management Commands
OPTIONS:
--shell value, -s value [ --shell value, -s value ]  Shell type to install completion
--help, -h                                           show help (default: false)
```
=> feat: add completion command

base-images/r4.2.Dockerfile
=> fix: Update python setuptools to python3

pkg/app/create.go, pkg/envd/docker.go, pkg/envd/envdserver.go, pkg/ssh/ssh.go
=> fix: Remove ir direct access in ssh

.github/workflows/CI.yml, .gitignore
=> chore: fix ci coverage reporter

pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/consts.go, pkg/lang/ir/v1/system.go
=> feat: support no default language in v1

pkg/lang/ir/v0/compile.go, pkg/lang/ir/v0/custom.go, pkg/lang/ir/v0/editor.go, pkg/lang/ir/v0/interface.go, pkg/lang/ir/v0/python.go, pkg/lang/ir/v0/types.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/editor.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/python.go, pkg/lang/ir/v1/types.go, pkg/types/envd.go, pkg/types/envd_test.go
* fix #1285
Need to fix both v0 & v1.
=> feat: install pypi packages in different groups

README.md
Preview: https://github.com/tensorchord/envd/blob/07af6ab019b9673500510fe7d1b3c8fb6ad123b0/README.md
=> fix: Update svg and simplify readme

pkg/lang/ir/v0/shell.go, pkg/lang/ir/v1/shell.go
Refer: https://starship.rs/presets/plain-text.html
=> fix: make starship prompt pure text

pkg/lang/frontend/starlark/v1/config/config.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/util.go
* fix the bug introduced in https://github.com/tensorchord/envd/pull/1286 cc @aseaday
=> fix: init uid/gid in Graph

README.md
=> doc: add more installation methods

pkg/types/envd.go
=> fix: Add more error info in env ls

README.md
=> chore: Use pip by default in readme

e2e/v1/docs/testdata/complex/build.envd, pkg/lang/ir/v1/system.go, pkg/lang/ir/v1/util.go
* fix https://github.com/tensorchord/envd/issues/1304
=> fix: v1 gpu base image name and envs

README.md
=> docs: Fix typos and correct cases

pkg/lang/ir/v0/conda.go, pkg/lang/ir/v1/conda.go
=> fix: conda meta permission for envd user

pkg/app/up.go
merge code in a `if` block
Signed-off-by: rrain7 [fefivesxh@gmail.com](mailto:fefivesxh@gmail.com)
=> refactor: combine code with the same logic

pkg/types/envd.go
=> fix: upgrade horust to support arm

examples/resnet-serving-v1/README.md, examples/resnet-serving-v1/build.envd, examples/resnet-serving-v1/client.py, examples/resnet-serving-v1/main.py
=> docs: add a serving example

envd/api/v1/config.py
=> docs: v1 config.owner

envd/api/v0/runtime.py, envd/api/v1/runtime.py
=> docs: update `envd exec` in envd api runtime command

go.mod, go.sum, pkg/app/login.go, pkg/envd/envdserver.go
Since we added a new API group about ssh key, this PR is to refactor the envd to support it.
=> feat(login): Refactor logic with the new key API

pkg/lang/ir/v0/conda.go, pkg/lang/ir/v0/custom.go, pkg/lang/ir/v0/python.go, pkg/lang/ir/v0/shell.go, pkg/lang/ir/v0/system.go, pkg/lang/ir/v0/user.go, pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/python.go, pkg/lang/ir/v1/shell.go, pkg/lang/ir/v1/system.go, pkg/lang/ir/v1/user.go
=> refact: change Shlex(fmt.Sprintf to Shlexf, use ` instead of escape \"

.github/ISSUE_TEMPLATE/config.yml
=> fix: doc url in envd github issue page

examples/pytorch2/README.md, examples/pytorch2/build.envd, examples/pytorch2/main.py
Signed-off-by: xuangong <xinglong@minimaxi.com>
https://github.com/tensorchord/envd/issues/1270
=> doc: add pytorch2 example

.github/workflows/envd-lint.yml, Makefile
=> fix: install black[jupyter] for CI check

.editorconfig
=> fix: remove duplicated config and fix Dockerfile pattern

base-images/r4.2.Dockerfile
Fix #1367 
Ref https://stackoverflow.com/questions/73251468/e-package-libssl1-1-has-no-installation-candidate
=> fix: Remove libssl1.1

base-images/r4.2.Dockerfile
=> fix: Update rstudio server

pkg/lang/ir/v0/cache.go, pkg/lang/ir/v0/conda.go, pkg/lang/ir/v0/custom.go, pkg/lang/ir/v0/python.go, pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/python.go, pkg/types/envd.go
=> chore: Use the same cacheID and llb.Scratch()

pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/python.go
This should fix the nightly test error.
=> fix: add conda&python path for non-conda mode

e2e/v0/language/runtime_test.go, e2e/v0/language/testdata/runtime/build.envd, e2e/v1/language/runtime_test.go, e2e/v1/language/testdata/runtime/build.envd, pkg/lang/ir/v0/user.go
=> fix: v0 user passwd, add test for root permission

pkg/buildkitd/buildkitd.go, pkg/docker/docker.go
=> fix: increase the default buildkit cache limit

pkg/buildkitd/buildkitd.go, pkg/docker/docker.go
=> Revert "fix: increase the default buildkit cache limit"

pkg/app/exec.go, pkg/envd/docker.go, pkg/envd/engine.go, pkg/envd/envdserver.go, pkg/lang/ir/types.go, pkg/lang/ir/util.go
=> feat: `envd exec` get runtime graph from container labels

pkg/lang/frontend/starlark/v0/config/config.go, pkg/lang/ir/v0/interface.go, pkg/lang/ir/v0/python.go, pkg/lang/ir/v0/types.go
=> feat(lang/py): add trust for pip_index

pkg/lang/frontend/starlark/v1/install/install.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/julia.go, pkg/lang/ir/v1/system.go, pkg/lang/ir/v1/types.go
This PR adds support for Julia environment and Julia package installation
To test:
```golang
def build():
base(dev=True)
install.julia()
install.julia_packages(name=["Example"])
install.julia_packages(name=["JSON","Random"])
```
Ready for review @kemingy 
Signed-off-by: Botong Ou <richard97@g.ucla.edu>
=> Support Julia environment and Julia package installation

e2e/v1/docs/testdata/julia/build.envd
=> fix: julia v1 test

pkg/app/build.go, pkg/app/build/build.go, pkg/app/destroy.go, pkg/app/up.go, pkg/docker/docker.go, pkg/docker/docker_test.go, pkg/lang/ir/v1/compile.go
* fix https://github.com/tensorchord/envd/issues/1398
=> fix: create a legal container env name from cur dir

pkg/lang/ir/v1/util.go
* fix https://github.com/tensorchord/envd/issues/1396
=> fix: v1 gid on darwin

envd/api/v0/config.py, envd/api/v1/config.py, envd/api/v1/install.py, pkg/lang/frontend/starlark/v1/config/config.go, pkg/lang/ir/v1/consts.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/python.go, pkg/lang/ir/v1/types.go
=> feat: support trust the pypi index in v1, add api doc

examples/llm-inference/8bit.py, examples/llm-inference/build.envd, examples/llm-inference/main.py
=> LLM inference example

pkg/lang/ir/v0/install-conda.sh, pkg/lang/ir/v0/install-mamba.sh, pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/install_conda.sh, pkg/lang/ir/v1/python.go
* refer to https://github.com/tensorchord/envd/discussions/1399#discussioncomment-4702637
* fix https://github.com/tensorchord/envd/issues/1409
=> fix: change default channel to `defaults`

pkg/builder/build.go
=> fix: Add docker auth

pkg/types/envd.go
=> feat: add `make` as a default system package

envd/api/v0/runtime.py, envd/api/v1/runtime.py
In case some users need to debug.
=> doc: add init and daemon debug guide

go.mod, go.sum, pkg/app/run.go, pkg/app/up.go, pkg/envd/docker.go, pkg/envd/envdserver.go, pkg/envd/types.go
* fix https://github.com/tensorchord/envd/issues/1429
=> feat: add shm size to start options

pkg/app/run.go, pkg/envd/docker.go, pkg/lang/ir/graph.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v0/types.go, pkg/lang/ir/v0/util.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/types.go, pkg/lang/ir/v1/util.go, pkg/lang/version/version.go, pkg/types/label.go
=> feat: support envd run in local docker context

.golangci.yml, pkg/driver/docker/docker.go, pkg/home/auth_test.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/julia.go, pkg/lang/ir/v1/r.go, pkg/progress/progressui/printer.go, pkg/shell/zsh.go, pkg/util/fileutil/namegenerator.go
=> chore: add unconvert to linters and address related issues

pkg/home/auth.go, pkg/home/cache.go, pkg/home/config.go, pkg/home/context.go, pkg/util/fileutil/file.go
=> fix: unify receiver type for generalManager

pkg/app/bootstrap.go, pkg/app/prune.go, pkg/builder/build.go, pkg/buildkitd/buildkitd.go, pkg/driver/docker/docker.go, pkg/home/context.go, pkg/home/manager.go, pkg/lang/ir/v0/supervisor.go, pkg/lang/ir/v1/supervisor.go, pkg/types/envd.go, pkg/version/version.go
I am not so familiar with every details in envd, so this is just a initial commit. Let me know any part that i should pay attention to when adding a new builder type.
Signed-off-by: Kaiyang-Chen <kaiyang-chen@sjtu.edu.cn>
=> feat: support buildx moby worker in docker 23.0.0 onward to accelerating building process by skipping docker load

.golangci.yml, cmd/envd-sshd/main.go, pkg/app/exec.go, pkg/builder/build.go, pkg/envd/factory.go, pkg/lang/ir/v0/editor.go, pkg/lang/ir/v0/shell.go, pkg/lang/ir/v1/editor.go, pkg/lang/ir/v1/shell.go, pkg/ssh/ssh.go, pkg/util/netutil/netutil.go
Add `revive` linter and enable `indent-error-flow` rule only.
=> fix: add revive and address indent-error-flow issues

e2e/v1/docs/julia_mnist_test.go, e2e/v1/docs/testdata/julia_mnist/build.envd, e2e/v1/docs/testdata/julia_mnist/mnist.jl
Here is the example of Julia doing a classification task on the MNIST dataset using traditional CNN.
It will print out an average accuracy on the test dataset.
=> Julia MNIST classification e2e test example

e2e/v1/docs/extra_lang_test.go, pkg/buildkitd/buildkitd.go, pkg/util/envutil/env.go, pkg/util/envutil/env_test.go
This was needed for me to get everything to run. I'd imagine other users might benefit from this as well.
=> feat: Allow buildkit timeout to be configurable

pkg/app/run.go, pkg/app/up.go, pkg/envd/docker.go, pkg/envd/types.go
=> feat: support CPU and memory limit for docker runner

Makefile
mockgen is not always on PATH.
=> build: FQN mockgen bin path

pkg/lang/ir/v1/editor.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/python.go, pkg/lang/ir/v1/system.go, pkg/lang/ir/v1/types.go
This is required by R because if you want to use tensorflow with R, it will require python environment.
Also, it is better to allow users to install multiple languages environment at the same time.
Related to #407, #1344
=> feat: Support installing multi-language environment at the same time

e2e/v1/docs/rlang_mnist_test.go, e2e/v1/docs/testdata/rlang_mnist/build.envd, e2e/v1/docs/testdata/rlang_mnist/mnist.r
Here is the MNIST deep learning example for R language using TensorFlow.
Related to #1344
=> e2e MNIST deep learning example for R

go.mod, go.sum, pkg/app/app.go, pkg/home/manager_test.go
refer to https://github.com/tensorchord/envd/pull/1518
=> fix: upgrade buildkit to fix the secury issue

envd/api/v0/runtime.py, envd/api/v1/runtime.py
- fix https://github.com/tensorchord/envd-docs/issues/277
=> docs: envd expose port should be int

pkg/app/bootstrap.go, pkg/app/completion.go, pkg/autocomplete/bash.go, pkg/autocomplete/fish.go, pkg/autocomplete/zsh.go
https://github.com/tensorchord/envd/issues/1377
Hi @hezhizhen, I found that `envd bootstrap` does not currently support autocomplete for fish shell, so I submitted a PR for it. If you're also working on implementing this, please let me know.
=> feat(CLI): add fish completion

pkg/app/init.go
firstly check if `build.envd` exisits, then prompt the user to overwrite the file with `--force` or set up a new environment with `envd up`
=> feat: friendly prompt when exec `envd init`

pkg/envd/types.go
This is introduced because of a bug in `progressbar`. It has been fixed now.
Refer:
- https://github.com/tensorchord/envd/pull/1460
- https://github.com/schollz/progressbar/releases/tag/v3.13.1
=> fix: remove the lock in progressbar

pkg/builder/util.go
=> fix: hard code amd64 to support remote build

e2e/v1/docs/rlang_mnist_test.go, e2e/v1/docs/suite_test.go
- fix https://github.com/tensorchord/envd/actions/runs/4727900879/jobs/8388938094
cc @oubotong
=> fix: rm the focus in docs v1 test

pkg/app/build/build.go, pkg/builder/build.go, pkg/builder/builder_test.go, pkg/lang/ir/graph.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v1/compile.go, pkg/progress/compileui/display.go, pkg/progress/mode/mode.go, pkg/progress/progresswriter/printer.go
Set progress mode in code, and fix: #1253 .
=> fix: In debug model, there is progress display.

pkg/app/bootstrap.go
=> fix: bootstrap with key pair using the same path for pri/pub key

pkg/lang/ir/v0/system.go, pkg/lang/ir/v1/system.go
- fix https://github.com/tensorchord/envd/issues/1618
=> feat: create dest path in io.copy

pkg/app/bootstrap.go, pkg/app/prune.go, pkg/builder/build.go, pkg/buildkitd/buildkitd.go, pkg/driver/client.go, pkg/driver/docker/docker.go, pkg/driver/nerdctl/nerdctl.go, pkg/util/buildkitutil/buildkit.go, pkg/util/buildkitutil/buildkit_test.go
=> refactor: use template for buildkit config file

.github/workflows/release.yml, .goreleaser.yaml
- According to https://goreleaser.com/deprecations/#archivesreplacements
=> chore: fix the goreleaser action and name template

pkg/app/bootstrap.go, pkg/driver/docker/docker.go, pkg/util/buildkitutil/buildkit.go, pkg/util/buildkitutil/buildkit_test.go
- fix: docker mirror configuration
- refactor: generate the buildkitd toml file and mount it into the container
=> fix: mount buildkitd toml file

.goreleaser.yaml
=> chore: fix the release artifact name

pkg/app/up.go
- close https://github.com/tensorchord/envd/issues/1519
=> feat: envd up with `--gpus`

pkg/builder/build.go, pkg/lang/ir/graph.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v0/types.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/python.go, pkg/lang/ir/v1/types.go, pkg/lang/ir/v1/util.go
- fix #https://github.com/tensorchord/envd/issues/1629
=> feat(v1): copy the requirements content if possible

Makefile
fix: https://github.com/tensorchord/envd/issues/1740
=> fix: add ldflags for debug-local

go.mod, go.sum
- fix the release error caused by `go mod tidy`: https://github.com/tensorchord/envd/actions/runs/7343727313/job/19994652738
=> fix: update docker/docker dependency

pkg/home/auth.go
Find an error comment while addressing issue #1804 .
=> fix: fix comment in /pkg/home/auth.go.

.github/workflows/release.yml, envd/api/v1/__init__.py, pkg/lang/ir/v1/conda.go
`micromamba install <pkgs>` will need to modify some directories under `/opt/conda`.
=> fix: chown all the files for mamba under `/opt/conda`

.github/workflows/release.yml, README.md, base-images/remote-cache/build-and-push-remote-cache.sh, base-images/remote-cache/build.envd, pkg/app/build.go, pkg/app/up.go, pkg/builder/build.go, pkg/lang/ir/v1/r.go, pkg/lang/version/version.go, pkg/types/envd.go
- fix https://github.com/tensorchord/envd/issues/1974
=> fix: use buildkit container builder to export cache

e2e/docs/testdata/complex/build.envd, envd/api/v0/config.py, envd/api/v1/config.py
- fix https://github.com/tensorchord/envd/actions/runs/13191900894/job/36826238091
=> fix: use ubuntu 22.04 mirror

pkg/app/new.go
- avoid the noise from https://github.com/tensorchord/envd-docs/pull/315
=> feat: emb the whole template/*.envd, avoid random map key order

pkg/lang/ir/v1/shell.go
- refer to https://github.com/fish-shell/fish-shell/discussions/11233
=> feat: bump fish to the official release version

pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/get_conda.sh, pkg/lang/ir/v1/system.go, pkg/types/envd.go
- revert https://github.com/tensorchord/envd/pull/1129, we use `starship` for prompt
- update miniconda
- related to https://github.com/tensorchord/envd/discussions/2009
=> fix: locale for both dev=True/False

pkg/app/template/pixi.envd, pkg/lang/ir/v1/pixi.go, pkg/lang/ir/v1/system.go
- add pixi tempalte
- rm unused const
=> feat: add pixi template

.github/dependabot.yml, .github/workflows/CI.yml, .github/workflows/changelog.yaml, .github/workflows/nightly.yml, .github/workflows/release.yml, .golangci.yml, pkg/app/init.go, pkg/app/run.go, pkg/driver/docker/docker.go, pkg/driver/nerdctl/nerdctl.go, pkg/lang/ir/v1/shell.go, pkg/progress/progressui/display.go
- upgrade the lint to v2
- group dependabot PRs
- fix the lint
=> chore: update to golangci-lint v2
