envd/api/__init__.py
Lacking this file will trigger the warning:
```
/python3.8/site-packages/setuptools/command/build_py.py:153: SetuptoolsDeprecationWarning:     Installing 'envd.api' as data is deprecated, please list it in `packages`.
!!
############################
############################
Python recognizes 'envd.api' as an importable package,
but it is not listed in the `packages` configuration of setuptools.
'envd.api' has been automatically added to the distribution only
because it may contain data files, but this behavior is likely to change
in future versions of setuptools (and therefore is considered deprecated).
Please make sure that 'envd.api' is included as a package by using
the `packages` configuration field or the proper discovery methods
(for …
```
=> fix: add api/__init__.py

.github/workflows/CI.yml
https://github.community/t/why-is-docker-not-installed-on-macos/17017/7
Docker cannot be installed in GitHub macOS runners. Thus we disable the unit test for macOS. We just build the binary.
=> fix: Disable unit test in macOS

go.mod, go.sum
ref: https://github.com/distribution/distribution/issues/3590
close: #316 
manually bump `distribution` to `v2.8.1`
this works on my mac arm64, please have a try to verify it.
=> chore(dep): manually bump docker distribution 2.8.1

examples/conda/build.envd, pkg/app/destroy.go, pkg/editor/jupyter/util.go, pkg/lang/frontend/starlark/install/install.go, pkg/lang/frontend/starlark/universe/universe.go, pkg/lang/ir/compile.go, pkg/lang/ir/conda.go, pkg/lang/ir/interface.go, pkg/lang/ir/python.go, pkg/lang/ir/system.go, pkg/lang/ir/types.go, pkg/lang/ir/util.go, pkg/lang/ir/util_test.go
=> feat: Suport conda env

setup.py
Signed-off-by: Manjusaka <me@manjusaka.me>
=> fix: add classifiers in setup.py

.github/workflows/release.yml
=> fix: use python3 explicitly to avoid type hints error

go.mod, go.sum, pkg/util/netutil/netutil_test.go
Signed-off-by: Ye Sijun <junnplus@gmail.com>
Fixes: https://github.com/tensorchord/envd/issues/382
I tested it on my local (archlinux) and it works, so does the ubuntu VM.
=> fix: cannot assign requested address

pkg/lang/ir/compile.go
=> fix: Hack the gid

pkg/app/build.go, pkg/app/up.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/builder/util.go, pkg/builder/util_test.go
Closes #272 
```shell
$ envd build --output type=tar,dest=test.tar
```
The parameters follow `docker build --output`.
References:
- https://docs.docker.com/engine/reference/commandline/build/#options
=> feat(cli): support `envd build --output`

docs/README.md
=> docs: Fix incorrect link to documentation

pkg/lang/ir/system.go
When building R environment, we'll see the following error:
```
=> docker-image://docker.io/library/r-base:4.2.0                                                                                                                                0.6s
=> => resolve docker.io/library/r-base:4.2.0                                                                                                                                    0.6ss
=> 💽 (cached) [internal] create user group envd                                                                                                                                 0.0s
=> 💽 (cached) [internal] create user envd                                                                                                                                       0.0s
=> 💽 …
```
=> fix: Only configure conda for Python environment

pkg/buildkitd/buildkitd.go
Signed-off-by: Kevin Su <pingsutw@apache.org>
Related to https://github.com/tensorchord/envd/issues/397
=> Bootstrap gets error if the envd_buildkitd was stopped before

Makefile
The `make help` command should work on any *Nix OS.
The expected behavior:
Thanks to [ingress-nginx:Makefile](https://github.com/kubernetes/ingress-nginx/blob/main/Makefile#L63)
=> chore(Makefile): add `help` target

pkg/app/destroy.go
=> chore(destroy): add current path `.` as the default path

Makefile
After https://github.com/tensorchord/envd/pull/421, running `make` only triggers `make help` but it should trigger `make build`. This PR fixes that.
```
➜  envd git:(main) make
Usage:
make <target>
help             Display this help
build            Build the release version of envd
debug            Build the debug version of envd
lint             Lint GO code
generate         Generate mocks
addlicense       Add license to GO code files
test             Run the tests
clean            Clean the outputs and artifacts
fmt              Run go fmt against code.
vet              Run go vet against code.
```
=> build: Plain make command only prints out help

pkg/lang/ir/compile.go, pkg/lang/ir/system.go
The UID is not set properly. Thus the pip cache dir is owned by root user. This PR is to fix it.
=> fix: Fix the bug about uid

base-images/build.sh, base-images/r4.2.Dockerfile, pkg/lang/ir/system.go
=> feat: Add base image for R language

pkg/docker/docker.go
This was useful when debugging issues like https://github.com/tensorchord/envd/issues/459.
=> feat: Print out container info when wait timeout

pkg/app/app.go, pkg/app/prune.go, pkg/buildkitd/buildkitd.go, pkg/buildkitd/mock/mock.go, pkg/buildkitd/print.go, pkg/home/manager.go
=> feat(CLI): Prune cache

go.mod, pkg/app/version.go, pkg/docker/docker.go, pkg/envd/engine.go, pkg/types/envd.go, pkg/version/version.go
- Add extra doctor information in `version` by `--detail`
fix #283 
No.
Signed-off-by: Popfido <wanghailin317@gmail.com>
=> feat(CLI): Add '--detail' for detail version information (#283)

pkg/app/up.go
feat #246
Signed-off-by: kenwoodjw
=> feat #246: envd up a GPU image without GPUs 

base-images/build.sh, examples/r-basic/build.envd, pkg/lang/ir/compile.go, pkg/lang/ir/r.go, pkg/lang/ir/system.go
This PR is to fix the broken R support.
You can use all envd primitives such as `shell`, in R.
=> feat(lang): Support R language

pkg/app/bootstrap.go, pkg/app/build.go, pkg/app/up.go, pkg/ssh/config/key.go, pkg/ssh/config/ssh_config.go, pkg/util/fileutil/namegenerator.go
Change:
- When use specify a new key in `envd bootstrap`, the old key will be copied to a new one with a random name. And the entries in ssh config file is changed accordingly
- The ssh flag in up and build is kept but turned to hidden
=> feat(ssh): Config ssh key permanently and globally

pkg/lang/ir/julia.go
Fix the following bug when install multiple Julia pkgs
```julia
Pkg.add("IJulia", "Example")
```
```
=> ERROR install julia packages                                                                                                                                                                            6.0s
------
> install julia packages:
#0 0.737 ERROR: MethodError: no method matching add(::String, ::String)
#0 5.958 Closest candidates are:
#0 5.958   add(::Union{AbstractString, Pkg.Types.PackageSpec}; kwargs...) at /usr/local/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:143
#0 5.958 Stacktrace:
#0 5.958  [1] top-level scope
#0 5.958    @ none:1
------
ERRO[2022-06-28T13:50:32+08:00] failed to load docker image: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.41/images/load?quiet=1": context …
```
=> Fix Julia multiple pkg installation bug

.gitignore, go.mod, go.sum, pkg/app/build.go, pkg/app/up.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/builder/util.go, pkg/builder/util_test.go
Fix #201 
Ref #510 
```
To build an image using build.envd:
$ envd build
To build and push the image to a registry:
$ envd build --output type=image,name=docker.io/username/image,push=true
```
=> feat(CLI): Add push

pkg/buildkitd/buildkitd.go, pkg/docker/docker.go
fix https://github.com/tensorchord/envd/issues/478
=> feat: replace IsCreated with Exists for Client interface from package docker

pkg/app/build.go, pkg/app/up.go, pkg/docker/docker.go, pkg/docker/docker_suite_test.go, pkg/docker/docker_test.go
- rename the image tag do lowcased if reference has some uppers
- throw error if the directory  just a digest [a-z0-9]{64}
=> Fix: image tag normalized to docker spec

pkg/app/up.go, pkg/builder/builder.go, pkg/docker/docker.go
=> feat: Support for build image update when exec build or up again

pkg/app/destroy.go, pkg/docker/docker.go
Make sure users get useful messages.
=> chore: update envd destroy cmd log msg

pkg/app/up.go
Fixes https://github.com/tensorchord/envd/issues/450
Signed-off-by: Guangyang Li <bot@guangyangli.com>
=> Use DefaultText in up.go

cmd/envd/main.go, pkg/remote/sshd/sshd.go
This fixes the following error lint checks:
```
comparing with == will fail on wrapped errors. Use errors.Is to check for a specific error
type assertion on error will fail on wrapped errors. Use errors.As to check for specific errors
```
=> chore: Improve error wrapping and checking

pkg/app/build.go, pkg/app/up.go, pkg/builder/build.go, pkg/builder/builder.go, pkg/builder/builder_test.go, pkg/buildkitd/buildkitd.go, pkg/buildkitd/mock/mock.go, pkg/flag/consts.go
=> feat(builder): Abstract BuildFunc to use gateway client

pkg/app/build.go, pkg/app/up.go, pkg/builder/build.go, pkg/builder/builder.go, pkg/builder/util.go, pkg/builder/util_test.go, pkg/lang/ir/conda.go, pkg/lang/ir/python.go, pkg/lang/ir/system.go
=> feat(CLI): Support cache

e2e/bytecode_hash_test.go, e2e/e2e_helper.go, e2e/quick_start_test.go, pkg/builder/builder.go, pkg/docker/docker.go, pkg/docker/label.go, pkg/lang/frontend/starlark/interpreter.go, pkg/lang/frontend/starlark/interpreter_test.go, pkg/lang/frontend/starlark/starlark_suite_test.go, pkg/lang/frontend/starlark/testdata/test.envd, pkg/types/label.go
More accurate image cache based on the compiled bytecode'hash.
See e2e/bytecode_hash_test.go for more details.
https://github.com/tensorchord/envd/issues/631
https://github.com/tensorchord/envd/issues/553
=> feature:  add label ai.tensorchord.envd.build.manifestBytecodeHash to image for cache robust

pkg/lang/frontend/starlark/install/install.go, pkg/lang/ir/system.go
Add default PATH env var to avoid problems like `starting container process caused: exec: "mim": executable file not found in $PATH`
=> fix: Add environment variable PATH in run

README.md
=> docs: Mention support for other languages

e2e/e2e_helper.go, e2e/quick_start_test.go, pkg/app/app.go, pkg/app/bootstrap.go, pkg/app/build.go, pkg/app/env_describe.go, pkg/app/run.go, pkg/app/up.go, pkg/builder/builder_test.go, pkg/ssh/config/key.go, pkg/ssh/config/ssh_config.go, pkg/ssh/ssh.go
Ref #11 
```
NAME:
envd run - Spawns a command installed into the environment.
USAGE:
envd run [command options] [arguments...]
OPTIONS:
--command value, -c value  Command to execute
--name value, -n value     Name of the environment
```
```
$ envd run --name python-basic --command "pip list"
Package            Version
------------------ ---------
certifi            2022.6.15
charset-normalizer 2.1.0
idna               3.3
pip                22.1.2
requests           2.28.1
setuptools         61.2.0
urllib3            1.26.10
via                0.0.2
wheel              0.37.1
```
=> feat(CLI): Support run command

pkg/app/app.go, pkg/app/bootstrap.go, pkg/app/build.go, pkg/app/const.go, pkg/app/context.go, pkg/app/destroy.go, pkg/app/env.go, pkg/app/image.go, pkg/app/init.go, pkg/app/pause.go, pkg/app/prune.go, pkg/app/resume.go, pkg/app/run.go, pkg/app/up.go, pkg/app/version.go
The new help text looks like:
```
envd - Development environment for data science and AI/ML teams
Usage:
envd up --path <path>
envd run --name <env-name> --command "pip list"
Build and launch envd environments. Get more information at: https://envd.tensorchord.ai/.
To get started with using envd, check out the getting started guide: https://envd.tensorchord.ai/guide/getting-started.html.
Advanced Commands:
pause, p   Pause the envd environment
resume, r  Resume the envd environment
Basic Commands:
build, b          Build the envd environment
destroy, d        Destroy the envd environment
envs, env, e      Manage envd environments
images, image, i  Manage envd images
run               Spawns a command installed into the environment.
up, u             Build and run the envd environment …
```
=> feat(CLI): Add category and refine help text

pkg/lang/ir/conda.go, pkg/lang/ir/python.go
=> feat(lang): Add default conda pkg cache

pkg/docker/docker.go, pkg/lang/frontend/starlark/io/const.go, pkg/lang/frontend/starlark/io/io.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
Related: https://github.com/tensorchord/envd/issues/673
Support `io.mount(src=...., dest=...)` to mount host directory into container when `envd up`.
For example using dgl
```
io.mount(src="~/.envd/data/dgl", dest="~/.dgl")
```
In future we can simplify the experience, for example `io.mount(src=Envd("dgl"), dest=io.const.dgl_data_path)`
=> feat: support io.mount

.github/dependabot.yml
The default time is quite earlier 3am in China and on Saturdays. This new schedule would make more sense.
=> ci: Change dependabot PRs to China workday morning time

.github/workflows/CI.yml, .github/workflows/release.yml, .goreleaser.yaml, Makefile, base-images/build.sh, base-images/python3.9-ubuntu20.04-cuda11.6.Dockerfile, base-images/python3.9-ubuntu20.04.Dockerfile, base-images/remote-cache/build-and-push-remote-cache.sh, base-images/remote-cache/build.envd, e2e/e2e_helper.go, e2e/suite_test.go, examples/python-basic/build.envd, go.mod, pkg/app/version.go, pkg/builder/build.go, pkg/builder/builder.go, pkg/lang/ir/compile.go, pkg/lang/ir/conda.go, pkg/lang/ir/install-conda.sh, pkg/lang/ir/python.go, pkg/lang/ir/system.go, pkg/lang/ir/util.go, pkg/version/version.go
Ref #667 
This PR is to:
- Move conda installation into ir package (which means that it is re-implemented with llb.State)
- Add default remote cache for python 3.9 in base-images/remote-cache.
- Add envd version tag into base images.
- Support building remote cache and base images in CI
=> feat(base-image): Move conda to llb and cache it

Makefile, setup.py
* `make build` is deleted in #724
=> fix: setup.py build

base-images/remote-cache/build-and-push-remote-cache.sh, pkg/app/app.go, pkg/flag/consts.go, pkg/lang/ir/compile.go, pkg/lang/ir/conda.go, pkg/lang/ir/system.go
We create the dir /opt/conda with the specified uid and gid, thus the base image cache fails to work if the UID is not `1000`, this PR is to fix it.
Besides this, a new hidden global flag `docker-organization` is introduced for debugging purposes.
=> feat: Avoid gid in base image cache

pkg/builder/util.go, pkg/builder/util_test.go
* related to https://github.com/tensorchord/envd/issues/446#issuecomment-1210402886
=> fix: ParseFromStr, add unittest

README.md
Our doc is outdated, the 'get' cmd has been abandoned.
=> docs(README): Correct the cmd of get Jupyter Notebook endpoint

.github/workflows/release.yml, base-images/build.sh, pkg/lang/ir/system.go
1. detect version git tag for base image, set to `latest` if empty
2. update built.sh to add a tag env var, so that CI could use to change the tag to latest
3. update CI release to build a latest image when released, rebuilt one directly because there should be docker built cache to be used automatically.
Signed-off-by: Wei Zhang <kweizh@gmail.com>
=> fix(CLI): 🔨  use latest version for local build

.goreleaser.yaml
we don't depend on go as we install by downloading the binary from github
Signed-off-by: WeiZhang <kweizh@gmail.com>
=> fix(release): :hammer: drop go build dep for homebrew

pkg/lang/ir/editor.go
=> fix: remove unnecessary if statement

README.md, examples/mnist/build.envd, pkg/app/template/python.envd
There is no need to add `token=""` in jupyter func.
=> fix: Remove empty token arg

docs/proposals/20220812-daemon-service.md
=> proposal: daemon process

examples/python-basic/build.envd, pkg/builder/util.go, pkg/lang/frontend/starlark/runtime/const.go, pkg/lang/frontend/starlark/runtime/runtime.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
=> feat(lang): add daemon function to run daemon process in the container

pkg/lang/frontend/starlark/runtime/runtime.go
The warning may not be noticed by users.
Let it panic so users know something wrong in the `envd` file.
=> fix: panic if daemon command is invalid

pkg/builder/builder_test.go, pkg/docker/docker.go, pkg/lang/ir/interface.go, pkg/lang/ir/util.go, pkg/metrics/collector.go, pkg/remote/sshd/os.go, pkg/ssh/config/ssh_config.go, pkg/ssh/ssh.go, pkg/util/ziputil/unzip.go
* https://github.com/tensorchord/envd/issues/27
=> fix: use cockroachdb errors

pkg/app/env_describe.go, pkg/app/image_describe.go, pkg/envd/engine.go, pkg/types/envd.go
* close https://github.com/tensorchord/envd/issues/782
=> feat(CLI): envd env describe expose info

examples/include_pkg/build.envd, pkg/lang/frontend/starlark/interpreter.go, pkg/lang/frontend/starlark/universe/const.go, pkg/lang/frontend/starlark/universe/universe.go, pkg/util/fileutil/file.go
* close #559
> Why not `load` or `import`?
`load` is starlark keyword, `import` has been reserved by starlark.
=> feat(lang): support include other git repo for envd functions/variables

envd/api/runtime/__init__.py, pkg/lang/frontend/starlark/runtime/runtime.go
=> fix(lang): expose host port

.github/workflows/auto-merge.yml
This would unblock the auto-merge for dependabot PRs.
=> ci: Switch to use GH_TOKEN env var for auto-merge workflow

pkg/ssh/ssh.go
Signed-off-by: VoVAllen <allenzhou@tensorchord.ai>
The right command to attach to container is `ssh mnist.envd`
=> bug: Fix detach instruction message

pkg/util/fileutil/file.go
Previously, this will still trigger the `NoErrAlreadyUpToDate` error.
=> fix: include update repo

pkg/app/build.go, pkg/lang/frontend/starlark/data/const.go
`--output does not work, this PR is to fix it.
=> fix(CLI): Fix build output argument and huggingface integration

pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/universe/universe.go, pkg/lang/ir/conda.go, pkg/lang/ir/install-conda.sh, pkg/lang/ir/install-mamba.sh, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
Signed-off-by: Keming kemingyang@tensorchord.ai
Add the following code to your `~/.config/envd/config.envd` to try this new feature:
```py
config.conda_channel(use_mamba=True)
```
=> feat: support micromamba as an alternative to miniconda

pkg/lang/ir/install-conda.sh
According to:
* The founder of Anaconda https://www.reddit.com/r/Python/comments/iqsk3y/comment/gqdqrk9/
* Anaconda FAQ https://www.anaconda.com/blog/anaconda-commercial-edition-faq
I guess we should be able to use `miniconda` with the `conda-forge` channel.
BTW, we already support `micromamba` as an alternative. Although the CLI is not 100% compatible.
=> chore: use conda-forge as default miniconda channel

setup.py
Since [cibuildwheel v2.9.0](https://github.com/pypa/cibuildwheel/releases/tag/v2.9.0), CPython 3.11 wheels are built by default.
=> chore: add py3.11

pkg/lang/ir/conda.go, pkg/lang/ir/system.go
* fix #960 
* fix #897 
* Also, #933 is pending because of the same issue.
=> fix(ir): `apt install` and `conda env create` cache

pkg/lang/frontend/starlark/install/install.go, pkg/lang/frontend/starlark/universe/universe.go, pkg/lang/ir/compile.go, pkg/lang/ir/consts.go, pkg/lang/ir/interface.go
=> fix(ir): make sure default value won't be replaced with empty value

cmd/envd-sshd/main.go, pkg/app/ssh.go, pkg/remote/sshd/sshd.go, pkg/ssh/ssh.go
> If you don't specify a host key, it will generate one every time. This is convenient except you'll have to deal with clients being confused that the host key is different. It's a better idea to generate or point to an existing key on your system:
https://pkg.go.dev/github.com/gliderlabs/ssh@v0.3.5
The host key in envd-sshd is generated every time. Thus the fingerprint of the sshd always changes. This PR is to add a cli argument to support custom host key.
Ref #101 
=> feat: Support cli argument for host key

docs/proposals/20220603-kubernetes-vendor.md, pkg/app/create.go, pkg/app/up.go, pkg/envd/factory.go, pkg/ssh/ssh.go, pkg/types/envd.go, pkg/util/netutil/netutil.go, pkg/util/netutil/netutil_test.go
=> feat(context): Get ssh hostname from context, instead of hard-coded string

.gitignore, MANIFEST.in, Makefile, setup.py
=> bug: Fix install from source will lose version information

pkg/autocomplete/zsh.go
resolves: #552 
- Change envd's zsh-completion script name to `.envd.zsh`
- Try to write the `.envd.zsh` by the following methods:
1. write `/usr/share/zsh/site-functions/.envd.zsh` directly.
2. write `/usr/local/share/zsh/site-functions/.envd.zsh` directly.
3. write `$HOME/.envd.zsh` directly and add loaded script into the `$HOME/.zshrc`
=> fix(zsh): ignore inserting zsh-completion if system don't have zsh shell

pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/system.go, pkg/lang/ir/types.go, pkg/ssh/ssh.go
Now each `run` command will form a separate `bash -c` script, which makes context clean and is better for cache
=> chore: Regroup run command

base-images/horust.Dockerfile, pkg/lang/ir/compile.go, pkg/lang/ir/editor.go, pkg/lang/ir/shell.go, pkg/lang/ir/supervisor.go, pkg/lang/ir/system.go, pkg/lang/ir/user.go, pkg/types/envd.go
=> feat: use horust as the dev container supervisor

.gitignore, .vscode/launch.json, Makefile
With this PR, we can debug a binary built with `make debug-local` in vscode easily.
=> feat: enable convenient vscode debugging

envd/api/config/__init__.py, pkg/lang/frontend/starlark/config/config.go, pkg/lang/frontend/starlark/config/const.go, pkg/lang/ir/compile.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go, pkg/types/envd.go, pkg/types/label.go
This will add repo information to the image label. Thus server can clone this into containers when needed.
=> feat: add config.repo in envd

pkg/envd/docker.go, pkg/lang/frontend/starlark/runtime/runtime.go, pkg/lang/ir/interface.go, pkg/lang/ir/types.go
https://github.com/tensorchord/envd/issues/923
It will support the following features;
```python
def build():
base(os="ubuntu20.04", language="python3")
runtime.expose(envd_port=4400, listen_addr="172.22.90.240")
```
The container will listen on
```
784d93897bf6   envd-quick-start:dev    "horust"      56 seconds ago   Up 54 seconds   127.0.0.1:42277->2222/tcp, 172.22.90.240:40767->4400/tcp   envd-quick-start
```
PS:
- The parameter don't work in envd-server 
- It didn't influence the ssh port, I opened a new issue for this. https://github.com/tensorchord/envd/issues/1111
- There will be problems for multi NIC machine. I will fix it asap.
=> feat: Add listening_addr to expose fun

.github/workflows/CI.yml, .github/workflows/nightly.yml, pkg/app/app.go, pkg/app/telemetry/reporter.go
=> fix: Disable telemetry in CI

pkg/lang/ir/conda.go, pkg/lang/ir/interface.go, pkg/lang/ir/julia.go, pkg/lang/ir/python.go, pkg/lang/ir/r.go, pkg/lang/ir/shell.go, pkg/lang/ir/system.go
Ref #1103 
The software mirror configuration and shell configuration are delayed. Thus the conda cache will always work no matter with the shells and mirrors.
=> fix: Fix the order to make conda cache always work

pkg/app/debug_llb.go, pkg/builder/util.go, pkg/lang/ir/system.go, pkg/types/envd.go
Close #183 
Test case:
```
def build():
shell("zsh")
```
Before the PR:
```
~/golang via 🅒 envd 
⬢ [envd]❯ l<tab>
~/golang via 🅒 envd 
⬢ [envd]❯ l   l
l              ldconfig.real  LISTMAX        logger         lsblk          lzcmp        
la             ldd            ll             login          LS_COLORS      lzdiff       
langinfo       LESS           ln             logname        LSCOLORS       lzegrep      
last           let            local          LOGNAME        lscpu          lzfgrep   
```
After the PR:
```
~/golang via 🅒 envd 
⬢ [envd]❯ l<tab>
~/golang via 🅒 envd 
⬢ [envd]❯ l
l              ldconfig.real  LISTMAX        logger         lsblk          lzcmp        
la             ldd            ll             login          LS_COLORS      lzdiff       
langinfo       LESS …
```
=> fix: Fix zsh tab issue

pkg/lang/ir/system.go
To avoid:
```console
Errno: (2) No such file or directory
sshd: child_process_main: Failed to exec the new process.
```
Since envd-sshd will use `$ENVD_WORKDIR` as the working directory.
=> fix: pre-create the workdir

.github/workflows/release.yml
The default uid in GitHub Actions is 1001.
The `runneradmin` is 1000:1000.
* close #1169
=> chore: run as 1000:1000 for image cache

pkg/app/env_describe.go, pkg/envd/docker.go, pkg/envd/envdserver.go, pkg/types/envd.go
Signed-off-by: AlexXi19 <alex2001314jjj@gmail.com>
https://github.com/tensorchord/envd/issues/551
Show service name in ports list as specified by the issue.  
Inspected `envd envs describe` for both jupyter notebook and R studio and verified that the names are correct.
=> feat: add name to `envd envs describe`

.github/workflows/CI.yml, Makefile
Signed-off-by: cutecutecat <starkind1997@gmail.com>
The action [cutecutecat/go-cover-merge](https://github.com/cutecutecat/go-cover-merge) makes the wrapper of [gocovmerge](https://github.com/wadey/gocovmerge).
**Caution: `actions/download-artifact@v3` will create a directory of `path`, and put the actual artifact file inside that path when using argument `path`**
So:
```
- name: Get cli e2e coverage report
uses: actions/download-artifact@v3
with:
name: e2e-cli-coverage-out
path: e2e-cli-coverage.out
```
will lead to a path of `e2e-cli-coverage.out/e2e-cli-coverage.out`
will close #636
=> feat: merge coverage file and report to goverall

.golangci.yml
This PR removes three linters which are deprecated and replaced by the `unused` linter.
```bash
➜  ~/github/envd git:(main) golangci-lint run --max-same-issues 0 --max-issues-per-linter 0
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused.
```
=> chore: remove deprecated linter

pkg/lang/frontend/starlark/v1/config/config.go, pkg/lang/frontend/starlark/v1/config/const.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/types.go, pkg/lang/ir/v1/util.go, pkg/types/envd.go
This is a extra pr for #410.
There three ways to set UID/GID during building:
1. read args from cli
2. config.owner in build.envd
3. get current user's uid/gid
and their priorities.
=> Add config.owner to v1 syntax for setting UID and GID

Makefile, pkg/app/completion.go, pkg/autocomplete/bash.go, pkg/autocomplete/zsh.go
Signed-off-by: Frost Ming <me@frostming.com>
* * *
I am adding a formula for envd to homebrew (https://github.com/Homebrew/homebrew-core/pull/118130). Homebrew can manage the autocompletion script, we only need to provide the completion script, without installing it. 
Add an option to `completion` command to output the script only.
=> feat: add option to output the completion script to terminal

README.md
Signed-off-by: Frost Ming <mianghong@gmail.com>
* * *
As the install script is available on the website, we hereby change the most recommended installation method to it, because it doesn't depend on any software other than `curl` and should be considered the most beginner-friendly.
=> docs: recommend one-line install script in README

e2e/v0/cli/init_test.go, e2e/v1/cli/init_test.go, pkg/app/init.go, pkg/app/interactive.go
Pull request to address build failing [here](https://github.com/Homebrew/homebrew-core/pull/118300) and other CI contexts. 
Uses the [go-isatty](https://github.com/mattn/go-isatty) package to detect terminal and disable interactive cli if terminal doesn't exist. 
If terminal doesn't exist, the default `build.envd` generated is: 
```python 
def build():
base(os="ubuntu20.04", language="python")
```
Added back previously removed cli init tests.
=> chore: disable interactive cli if no tty

.github/workflows/release.yml, pyproject.toml, setup.py, venv/pyvenv.cfg
Signed-off-by: Frost Ming <mianghong@gmail.com>
* * *
The approach is taken from [cibuildwheel Tips and Tricks](https://cibuildwheel.readthedocs.io/en/stable/faq/#abi3), also quote:
>The CPython Limited API is a subset of the Python C Extension API that's declared to be forward-compatible, meaning you can compile wheels for one version of Python, and they'll be compatible with future versions. Wheels that use the Limited API are known as ABI3 wheels.
This will reduce the number of wheels to upload to PyPI
=> feat: produce ABI-agnostic wheels for python

pkg/lang/ir/types.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/r.go, pkg/lang/ir/v1/system.go
Related to the issue: https://github.com/tensorchord/envd/issues/1298
Implement internal functions that help to standardize the way for adding apt-sources using [DEB822](https://manpages.debian.org/buster/apt/sources.list.5.en.html) format. Created a structure that helps to configure the apt-sources:
```golang
type AptConfig struct {
Name       string
Enabled    string
Types      string
URIs       string
Suites     string
Components string
Signed     string
Arch       String
}
```
The R environment is hardcoded as the following using official mirror:
```golang
var sign = "https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc"
var aptConfig = ir.AptConfig{
Name:       "R-base",
Enabled:    "yes",
Types:      "deb",
URIs:       "https://cloud.r-project.org/bin/linux/ubuntu", …
```
=> feat: Support installing R environment in DEB822 format using internal standardized structure

pkg/app/context_ls.go, pkg/app/env_describe.go, pkg/app/env_ls.go, pkg/app/formatter/data.go, pkg/app/formatter/json/context.go, pkg/app/formatter/json/env.go, pkg/app/formatter/json/image.go, pkg/app/formatter/json/print.go, pkg/app/formatter/json/version.go, pkg/app/formatter/table/context.go, pkg/app/formatter/table/env.go, pkg/app/formatter/table/image.go, pkg/app/formatter/table/version.go, pkg/app/image.go, pkg/app/image_describe.go, pkg/app/version.go
close #1314 
- verson
- context ls
- image ls
- image describe
- env ls
- env describe
Signed-off-by: cutecutecat <starkind1997@gmail.com>
Original:
```shell
$ sudo ./envd context ls              
CONTEXT                 BUILDER                 BUILDER ADDR                            RUNNER  RUNNER ADDR 
default (current)       docker-container        docker-container://envd_buildkitd       docker
```
Help page:
```shell
$ sudo ./envd context ls -h
NAME:
envd context ls - List envd contexts
USAGE:
envd context ls [command options] [arguments...]
OPTIONS:
--format value, -f value  Format of output, could be "json" or "table" (default: "table")
--help, -h                show help (default: false)
```
Bad input:
```shell
$ sudo ./envd context ls --format apple
error: Argument format only …
```
=> feat: add --format for commands to output json

pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/user.go
* fix https://github.com/tensorchord/envd/issues/1345
This legacy code is because the r-base image already has the 1000:1000. Since we don't relay on the r-base image anymore, we no longer need the 1001 trick.
=> fix: v1 change default user group to 1000:1000

pkg/ssh/ssh.go
=> fix: fix nil pointer dereference when exiting shell

pkg/envd/docker.go, pkg/types/envd.go
Fix #1372 
Ref https://github.com/tensorchord/envd/commit/0a975de0103d84841252b54b549cddaa6d82d8a6#diff-e2ddd9833874ac79a5e345e2cdb9293b6fa55ab86269dc103de3b27c9288bb77R520
In this func a image list is run. Then it will return an error if there is any broken image.
I run envd destroy --name mnist, it returns an error because python-basic is broken.
=> fix(CLI): Remove image list in destroy

pkg/lang/ir/types.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v0/conda.go, pkg/lang/ir/v0/julia.go, pkg/lang/ir/v0/system.go, pkg/lang/ir/v0/types.go, pkg/lang/ir/v0/user.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/julia.go, pkg/lang/ir/v1/system.go, pkg/lang/ir/v1/types.go, pkg/lang/ir/v1/user.go, pkg/types/envd.go
* fix #1346 
* runtime env
* build time path
* init
* renew when switch the user
* maintain it in the Graph (RuntimeEnvPaths)
* init as the system PATH
* update if needed
---
*Note*: runtime env PATH leaks to build time
=> fix: change to dynamic PATH

pkg/ssh/config/entry.go
Fix: https://github.com/tensorchord/envd/issues/1269
=> Optimize the logic of adding entry in wsl

e2e/v1/docs/testdata/julia/build.envd, envd/api/v1/install.py, pkg/lang/frontend/starlark/v1/install/install.go
One more thing, only `install.julia_packages` use `names` instead of `name`. Shall we align them? cc @VoVAllen @gaocegege
=> docs: v1 r_lang and julia packages

pkg/lang/ir/v0/python.go, pkg/lang/ir/v1/python.go
Switching users would be complex. It needs re-set all the environment variables.
The old version also takes longer to start installing (tested on WSL, it takes more than 15s to start).
=> fix: pip install requirements.txt

.github/workflows/nightly.yml
Signed-off-by: Wei Zhang <kweizh@gmail.com>
we can now only use conditions under jobs to prevent running on forks, it could be changed if https://github.com/community/community/discussions/16109 make any progress
=> ci: :hammer: only run nightly on main repo

pkg/lang/ir/v1/compile.go
We don't have the remote cache for v1. It only slows down the 1st build.
=> fix: rm remote cache for v1

go.mod, go.sum, pkg/builder/build.go
=> fix: pass loop variable as a function parameter

.golangci.yml
This will get rid of the warning when running lint check:
```
level=warning msg="[linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649
```
=> ci: Remove rowserrcheck linter to avoid warning

.github/workflows/CI.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, go.mod
v1.18 has reached end of life: https://endoflife.date/go
=> chore: Upgrade Go to v1.19

Makefile
Also add prompts for local build. It's intended to be omitted on release build.
It looks like:
```
$ make
Building envd ...
Building envd-sshd ...
Build envd successfully!
```
=> build: Reduce more redundant output

pkg/lang/ir/v1/compile.go
refer to #1553 
The change is to bring apt-source compilation earlier which allow some packages installed in
```python
if g.Dev {
dev := g.compileDevPackages(aptMirror)
sshd := g.compileSSHD(dev)
horust := g.installHorust(sshd)
starship := g.compileStarship(horust)
userGroup := g.compileUserGroup(starship)
aptMirror = userGroup
}
```
to use apt mirror.
In my PC, I've conducted some tests with `build.envd`
```python
base(image="ubuntu:22.04",dev=True)
install.conda()
install.python()
install.python_packages(requirements="requirements/dev.txt")
runtime.init(["make install"])
```
`install builtin packages` costs 358s and `envd up` cost 8min20s overall.
`envd up` cost 2min10s overall.
`install builtin packages` costs  26s and `envd up` cost 3min24s overall.
`envd up` cost 2mins overall.
=> feat: bring apt-source compilation earlier

pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/editor.go
refer to #1563
Currently, the vscode extensions are installed from `llb.Scratch()`, so some softwares could be installed in /root instead of user envd homeDir.
envd up with
```
def rust():
"""Install Rust."""
install.apt_packages(name=["build-essential"])
run(
[
"curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y",
]
)
runtime.environ(extra_path=["/home/envd/.cargo/bin"])
def build():
base(dev=True)
rust()
install.vscode_extensions(["rust-lang.rust-analyzer"])
runtime.init(["make install"])
```
In container,
```bash
⬢ [envd]❯ ls ~ -a
.  ..  .bash_logout  .bashrc  .cache  .config  mosec  .profile  .vscode-server
⬢ [envd]❯ sudo ls /root -a
.  ..  .bashrc  .cargo  .profile  .rustup  .zshenv
```
.cargo and .rustup are installed in wrong path `/root`.
```bash
⬢ [envd]❯ ls …
```
=> fix: compile vscode extensions with user state

pkg/editor/vscode/types.go, pkg/editor/vscode/util.go, pkg/editor/vscode/vscode.go, pkg/lang/ir/v1/editor.go
refer to #1565 
Currently, envd download extension via https://open-vsx.org/api/Publisher/Extension/latest. Let's take "ms-python.python" and "rust-lang.rust-analyzer" as instances.
When visiting https://open-vsx.org/api/rust-lang/rust-analyzer/latest , you can see the response json like,
there's several links to download extension in different platforms.
When visiting https://open-vsx.org/api/ms-python/python/latest , you can see the response json like,
there's several links to download extension in a universal platform.
Since envd take json["files"]["download"] link as extension download link `return files["download"].(string), nil`,it works for extensions in universal platform, but for extensions like rust-analyzer, the json["files"]["download"] link is a download link for default …
=> feat: download VScode extension by platform

pkg/app/destroy.go
The previous behavior of `envd destroy` without both `--path` and `--name` flags was to attempt to delete the environment in the current working directory. This could result in accidental deletion of environments, as seen in issue #1336. This pull request prevents this behavior by adding additional user confirmation to `envd destroy` if both flags are not provided.
```
$ envd destroy
INFO[2023-04-22T06:49:10Z] image(sha256:1a891bf790ef45aec292f63a414fcc4338e1b9e911a313570fb592f9e316a50f) is destroyed 
INFO[2023-04-22T06:49:10Z] environment(envd-quick-start) is destroyed  
```
```
$ envd destroy
Are you sure you want to destroy container envd in the current directory? [Y/n]
```
Fixes: #1336
<strike>
Additionally, I have raised [another PR](https://github.com/tensorchord/envd-docs/pull/281) …
=> feat: confirm `envd destroy` when path and name are both empty

pkg/app/destroy.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/python.go, pkg/lang/ir/v1/system.go
1. `envd destroy` default is "yes"
2. reduce the LLB merge op if not necessary since diff + merge can take a long time
=> fix: reduce llb merge in language part if not necessary

pkg/lang/ir/v1/system.go
- Use default python in the base image
- Allow users to install Python packages even if they didn't specify `install.python`.
=> Use default python in the base image

pkg/lang/ir/v1/shell.go, pkg/lang/ir/v1/system.go
On Ubuntu:18.04:
```sh
⬢ [envd]❯ which bash
/bin/bash
```
We don't need this absolute path.
=> fix(v1): rm bash absolute path

pkg/lang/ir/v1/compile.go
Before this PR, Ubuntu:18.04 (which contains python2.7) will use the default system Python instead of the conda Python because the merge op will override the language packages layer.
=> fix: merge language packages to system packages

pkg/app/bootstrap.go, pkg/app/prune.go, pkg/builder/build.go, pkg/buildkitd/buildkitd.go, pkg/driver/client.go, pkg/driver/docker/docker.go, pkg/driver/nerdctl/nerdctl.go
- fix #https://github.com/tensorchord/envd/issues/1592
Usage:
```sh
envd bootstrap --ca ca=/home/self_ca/contoso.crt,key=/home/self_ca/modelz.key,cert=/home/self_ca/modelz.crt --m https://private-docker-registry.io
```
=> feat: support mirror ca for buildkitd

envd/api/v0/__init__.py, envd/api/v0/install.py, envd/api/v0/runtime.py, envd/api/v1/__init__.py, envd/api/v1/install.py, envd/api/v1/runtime.py
It seems that `https://github.com/crate-ci/typos` isn't catching some typos in the repo, such as this one: `programing`.
=> Documentation improvements (typos, grammar etc)

pkg/app/bootstrap.go, pkg/app/prune.go, pkg/builder/build.go, pkg/buildkitd/buildkitd.go, pkg/driver/client.go, pkg/driver/docker/docker.go, pkg/driver/nerdctl/nerdctl.go
Usage:
```sh
envd bootstrap --use-http
```
This will enable communicating with the remote registry with HTTP instead of the default HTTPS.
=> feat: support bootstrap buildkit with HTTP

pkg/app/bootstrap.go, pkg/app/prune.go, pkg/builder/build.go, pkg/buildkitd/buildkitd.go, pkg/driver/client.go, pkg/driver/docker/docker.go, pkg/driver/nerdctl/nerdctl.go
Usage:
```bash
envd bootstrap --registry 172.17.0.2:30000 --use-http
```
This will enable communicating with the local private registry with HTTP.
=> feat: support bootstrap buildkit with registry

CHANGELOG.md, hack/changelog.sh
=> chore: Remove dependabot upgrades from changelog. Fixes #1655

pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/system.go
Previously, PATH would be overridden when we needed to update the env.
=> fix(v1): keep the PATH from the base image

.goreleaser.yaml
- refer to: https://github.com/goreleaser/goreleaser/pull/1838/files
- https://goreleaser.com/customization/archive/
I'm not able to verify it locally since it won't reflect on the local files. It will **ONLY** be used when uploading to GitHub Artifacts.
=> chore: fix the goreleaser name template

pkg/lang/ir/v1/system.go
Previously, map is unordered, so the new path will have an arbitrary order.
Example Path:
New Image Path:
- Path With Current Implementation:
- Path With New Changes:
By using a map + slice, we can maintain ordering.
=> Fix PATH Order

pkg/app/bootstrap.go, pkg/driver/docker/docker.go, pkg/driver/nerdctl/nerdctl.go, pkg/util/buildkitutil/buildkit.go, pkg/util/buildkitutil/buildkit_test.go
`envd bootstrap --registry-config path_to_json_file`
Format:
Note that the "name" field is required. The other fields are all optional.
This will allow users to specify private Docker registries and the respective credentials. Under the hood, we parse these credentials and create a corresponding buildkit TOML file, as well as set up Docker bindings. This enables users to pull and push images from private Docker registries.
This is also completely backwards compatible with the existing "registry" and "registry-ca-keypair" command. We check that a user only specifies "registy-config" on its own, meaning that a user can't use both registry-config and registry or both registry-config and registry-ca-keypair.
The registry-config command also enables users to specify more than one registry now. …
=> support using json for registry config

pkg/app/bootstrap.go, pkg/app/build.go, pkg/app/run.go, pkg/app/up.go
The error is caused by `<image>`.
- ref to https://github.com/tensorchord/envd-docs/pull/291 build errors
=> docs: fix the cli doc build error

pkg/lang/ir/v1/conda.go
The whole `envd` env might be used by users when installing new packages.
This can be triggered by `conda install -c conda-forge mosec`.
```
PermissionError: [Errno 13] Permission denied: '/opt/conda/envs/envd/.condatmp'
ERROR conda.core.link:_execute(952): An error occurred while uninstalling package 'defaults/linux-64::openssl-3.0.9-h7f8727e_0'.
Rolling back transaction: done
[Errno 13] Permission denied: '/opt/conda/envs/envd/bin/c_rehash' -> '/opt/conda/envs/envd/bin/c_rehash.c~'
ERROR conda.core.link:_execute(952): An error occurred while uninstalling package 'defaults/linux-64::openssl-3.0.9-h7f8727e_0'.
Rolling back transaction: done
[Errno 13] Permission denied: '/opt/conda/envs/envd/include/openssl/aes.h' -> '/opt/conda/envs/envd/include/openssl/aes.h.c~'
()
```
Previously, we …
=> fix(v1): chown the whole envd conda env to user envd

.github/workflows/CI.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
- ref https://github.com/golang/go/issues/61431
For now, we only need to pin the version for e2e-cli-v1 test and release.
Will update this after it's fixed.
=> chore: pin ci go version to 1.19.10 to avoid the invalid host header

pkg/app/telemetry/reporter.go
It might fail due to the segmentio free plan limit (1,000 visitors/mo).
=> fix: suppress telemetry send err msg

MANIFEST.in
https://pypi.org/project/envd/#files  this source dist also contains an `envd` binary.
=> fix: prune bin from py source dist

pkg/app/app.go, pkg/driver/docker/docker.go
- close #1719 
I just found that the default `urfave/cli` error handler cannot print the full error backtrace messages.
Before:
```sh
error: invalid reference format
```
After:
```sh
FATA[2023-08-04T16:25:13+08:00] failed to parse the build options: failed to parse the name '_dir:dev', please provide a valid image name: invalid reference format
```
=> feat: add envd app exit handler

pkg/builder/build.go, pkg/builder/util.go, pkg/lang/ir/graph.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v0/system.go, pkg/lang/ir/v0/types.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/python.go, pkg/lang/ir/v1/system.go, pkg/lang/ir/v1/types.go
This only affects the `WorkingDir` in the image config.
`envd up` will override this (though the `dev` image's default `WorkingDir` is already changed from `/` to `/home/envd/<env_name>` in this PR).
cc @gaocegege @RichhLi
=> feat: inherit the workdir from base image for non-dev env

envd/api/v0/config.py, envd/api/v1/config.py, pkg/app/up.go, pkg/builder/build.go, pkg/builder/builder.go, pkg/lang/frontend/starlark/v0/config/config.go, pkg/lang/frontend/starlark/v0/config/const.go, pkg/lang/frontend/starlark/v1/config/config.go, pkg/lang/frontend/starlark/v1/config/const.go, pkg/lang/ir/graph.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v0/interface.go, pkg/lang/ir/v0/types.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/types.go
This PR add support for shm_size in build.envd.
related issue: https://github.com/tensorchord/envd/issues/1449
=> feat: add shm size support

pkg/app/up.go, pkg/builder/build.go, pkg/lang/ir/graph.go, pkg/lang/ir/v0/compile.go, pkg/lang/ir/v1/compile.go
Before this PR, the error message is:
```console
failed to start the envd environment: failed to create the container: Error response from daemon: No command specified
```
After this PR:
```console
FATA[2023-09-01T14:31:23+08:00] `envd up` only works for dev images. If you're using v1, please enable dev with `base(dev=True)`.
```
=> feat: abort when trying to run `envd up` on non-dev images

README.md, pkg/app/app.go, pkg/app/reference.go
We can maintain the reference code in this repo. Will delete the go module and go code in `envd-docs`.
=> feat: add the reference subcommand to generate the markdown doc

pkg/lang/ir/v0/interface.go
envd v0 only works for Ubuntu20.04 and non-dev custom base images. We should add some warning messages about the usage and attach the v1 document.
=> feat: warn about envd v0 `os` and `image` usage

pkg/app/up.go
Previously, `config.gpu()` will be ignored in `envd up`.
=> fix: allow cli --gpus to override config gpu

pkg/app/up.go, pkg/envd/docker.go, pkg/envd/docker_test.go, pkg/envd/types.go
```text
[user@localhost test]$ envd up -h
NAME:
envd up - Build and run the envd environment
USAGE:
envd up [command options] [arguments...]
CATEGORY:
Basic Commands
OPTIONS:
--tag value, -t value                                                     Name and optionally a tag in the 'name:tag' format (default: PROJECT:dev)
--name value                                                              environment name
--path value, -p value                                                    Path to the directory containing the build.envd (default: ".")
--volume value, -v value [ --volume value, -v value ]                     Mount host directory into container
--from file:func, -f file:func                                            Function to execute, format file:func (default: …
```
=> feat: envd up with --gpu-set

e2e/v0/cli/testdata/custom-image-test/build.envd, e2e/v1/cli/testdata/custom-image-test/build.envd, envd/api/v0/__init__.py, envd/api/v1/install.py, examples/custom-image/build.envd, examples/dpgen2/build.envd, pkg/lang/ir/v0/conda.go, pkg/lang/ir/v0/install-conda.sh, pkg/lang/ir/v0/python.go, pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/get_conda.sh, pkg/lang/ir/v1/python.go, setup.py
Python 3.9 will reach the EOL this October:
- https://www.python.org/downloads/
Most of the machine learning libraries should have 3.11 support.
WDYT cc @gaocegege
=> feat: upgrade to python 3.11

pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/shell.go, pkg/lang/ir/v1/types.go
- fix https://github.com/tensorchord/envd/issues/663
To use fish:
```python
def build():
base(dev=True)
shell('fish')
install.conda()
install.python()
```
=> feat: support fish shell

pkg/lang/ir/v1/conda.go, pkg/lang/ir/v1/python.go
- some missing command options: https://github.com/mamba-org/mamba/issues/3535
=> feat: upgrade to micromamba2

e2e/language/python_test.go, e2e/language/testdata/python/uv/build.envd, envd/api/v1/install.py, pkg/lang/frontend/starlark/v1/install/const.go, pkg/lang/frontend/starlark/v1/install/install.go, pkg/lang/ir/types.go, pkg/lang/ir/v1/compile.go, pkg/lang/ir/v1/interface.go, pkg/lang/ir/v1/system.go, pkg/lang/ir/v1/types.go, pkg/lang/ir/v1/util.go, pkg/lang/ir/v1/uv.go, pkg/metrics/docker_collector.go, pkg/types/envd.go
Try it with:
```python
def build():
base(dev=True)
install.uv()
shell("fish")
```
=> feat: support uv

pkg/lang/ir/v1/pixi.go, pkg/lang/ir/v1/uv.go, pkg/remote/sshd/sshd.go
Fix the panic when sshd exec with error:
```
panic: errors.As: *target must be interface or implement error, found *exec.ExitError
goroutine 65 [running]:
github.com/cockroachdb/errors/errutil.As({0x9dea60, 0xc000387860}, {0x90a780, 0xc0003878a0?})
/home/runner/go/pkg/mod/github.com/cockroachdb/errors@v1.11.3/errutil/as.go:49 +0x547
github.com/cockroachdb/errors.As(...)
/home/runner/go/pkg/mod/github.com/cockroachdb/errors@v1.11.3/errutil_api.go:194
github.com/tensorchord/envd/pkg/remote/sshd.getExitStatusFromError({0x9dea60, 0xc000387860})
/home/runner/work/envd/envd/pkg/remote/sshd/sshd.go:276 +0x59
github.com/tensorchord/envd/pkg/remote/sshd.sendErrAndExit(0xc0001f2070, {0x9e6ed8, 0xc0003ca1a0}, {0x9dea60, 0xc000387860})
/home/runner/work/envd/envd/pkg/remote/sshd/sshd.go:265 +0x24e …
```
=> fix: sshd handle the error
